export const partialOrder = {
  table: 'order',
  action: 'partial',
  keys: ['orderID'],
  filter: {account: 223024},
  data: [
    {
      orderID: '572fe645-91c8-1a47-5060-18f11630f38a',
      clOrdID: '',
      clOrdLinkID: '',
      account: 223024,
      symbol: 'XBTUSD',
      side: 'Buy',
      simpleOrderQty: null,
      orderQty: 100,
      price: 8500,
      displayQty: null,
      stopPx: null,
      pegOffsetValue: null,
      pegPriceType: '',
      currency: 'USD',
      settlCurrency: 'XBt',
      ordType: 'Limit',
      timeInForce: 'GoodTillCancel',
      execInst: 'ParticipateDoNotInitiate',
      contingencyType: '',
      exDestination: 'XBME',
      ordStatus: 'New',
      triggered: '',
      workingIndicator: true,
      ordRejReason: '',
      simpleLeavesQty: null,
      leavesQty: 100,
      simpleCumQty: null,
      cumQty: 0,
      avgPx: null,
      multiLegReportingType: 'SingleSecurity',
      text: 'order_1',
      transactTime: '2020-07-12T20:39:38.902Z',
      timestamp: '2020-07-12T20:39:38.902Z',
    },
  ],
};
